Ensure that our own snapshot DKMS aren't stripped

diff --git a/debian/tests/kernel-smoke-test b/debian/tests/kernel-smoke-test
--- a/debian/tests/kernel-smoke-test
+++ b/debian/tests/kernel-smoke-test
@@ -26,6 +26,12 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+ls -lah $(/sbin/modinfo --filename bcachefs)
+if [ $? -ne 0 ]; then
+  echo "Error: failed to ls the loaded module."
+  exit 1
+fi
+
 bcachefs version
 if [ $? -ne 0 ]; then
   echo "Error: failed to get bcachefs tools info."
